sonar.projectKey=inkwell-category-service
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/entity/**,**/config/**,**/repository/**,**/mapper/**,**/exception/**,**/util/**,**/*Application.java
