package com.inkwell.post.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import com.inkwell.post.entity.PostStatus;

/**
 * Request DTO for creating a new post
 * Contains all necessary information to create a post
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Request payload used to create a new blog post draft.")
public class CreatePostRequest {

    @NotNull(message = "Author ID is required")
    @Schema(description = "Unique identifier of the author creating the post.", example = "7", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer authorId;

    @NotBlank(message = "Title is required")
    @Schema(description = "Post title shown in the feed and detail page.", example = "How InkWell Ships Features", requiredMode = Schema.RequiredMode.REQUIRED)
    private String title;

    @NotBlank(message = "Content is required")
    @Schema(description = "Rich HTML content generated by the editor.", example = "<p>This is the article body.</p>", requiredMode = Schema.RequiredMode.REQUIRED)
    private String content; // Rich HTML content

    @Schema(description = "Short summary used on cards and previews.", example = "A quick look at our release workflow.")
    private String excerpt; // Optional summary of the post

    @Schema(description = "Optional featured image URL for the article header.", example = "https://cdn.inkwell.local/posts/cover.jpg")
    private String featuredImageUrl; // Optional featured image

    @Schema(description = "Initial publication status for the post.", example = "PUBLISHED")
    private PostStatus status;

    @Schema(description = "ID of the category this post belongs to.", example = "1")
    private Integer categoryId;

    @Schema(description = "IDs of the tags associated with this post.", example = "[1, 2, 3]")
    private List<Integer> tagIds;

    /**
     * Validation note: Slug is automatically generated from title on the server side,
     * so it's not included in the request
     */
}
