server:
  port: 8083

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/inkwell_comment
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  spring:
    config:
      import: "optional:configserver:"

logging:
  level:
    com.inkwell.comment: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
