sonar.projectKey=inkwell-auth-service
sonar.projectName=InkWell Auth Service
sonar.host.url=http://localhost:9000
sonar.login=${env.SONAR_TOKEN}
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/entity/**,**/config/**,**/repository/**,**/client/**,**/mapper/**,**/exception/**,**/filter/**,**/*Application.java
