sonar.projectKey=inkwell-payment-service
sonar.projectName=InkWell Payment Service
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/entity/**,**/config/**,**/repository/**,**/client/**,**/mapper/**,**/exception/**,**/*Application.java,**/*Record.java,**/*Store.java
