server:
  port: 8084

spring:
  application:
    name: category-service

  datasource:
    url: jdbc:mysql://localhost:3306/inkwell_category
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    show-sql: false

  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.inkwell.category: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true