CREATE DATABASE IF NOT EXISTS inkwell_auth;
CREATE DATABASE IF NOT EXISTS inkwell_post;
CREATE DATABASE IF NOT EXISTS inkwell_comment;
CREATE DATABASE IF NOT EXISTS inkwell_category;
CREATE DATABASE IF NOT EXISTS inkwell_media;
CREATE DATABASE IF NOT EXISTS inkwell_messaging;
